### ISSUE TITLE
Query where field = null returns null as string value.

### ISSUE THREAD

**Issue by cbarlow1993** [perbert27/sequelize-querystring-converter#1]
Attempting to query where field = null. 

null parses as the string value of 'null'.

I would expect that this would filter as null.

**Comment by bert2796** [comment]
I'm sorry for the super late response and thank you for the report. This is already fixed on the new version so hopefully, I can release it for tomorrow. Thanks again!

**Comment by cbarlow1993** [comment]
No worries, thanks for the repo. There might have been a similar issue with true/false but I think I reworked that to be 1/0.

**Comment by bert2796** [comment]
Cool, then I'll be waiting for your PR.
